{"name": "test_print13", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 15", "trace": "def test_print13():\n        num = 14\n        logging.info('i am writing logs...')\n        logger.info('i am writing logs 2...')\n        printknow2()\n>       assert num == 15\nE       assert 14 == 15\n\napiauto\\test_doit5.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "7e88e988-4094-4f2b-a11a-b48ea114d5b3-attachment.txt", "type": "text/plain"}], "start": 1685195446513, "stop": 1685195446513, "uuid": "f6131783-40ac-4782-ad23-b139a8487afb", "historyId": "5c84f781d22b7be0851bd3e9e748571e", "testCaseId": "3da96bdadbc715439175681859fa033d", "fullName": "apiauto.test_doit5#test_print13", "labels": [{"name": "parentSuite", "value": "apiauto"}, {"name": "suite", "value": "test_doit5"}, {"name": "host", "value": "zhangtaopc"}, {"name": "thread", "value": "11624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "apiauto.test_doit5"}]}